server:
  port: 6400

spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        git:
          uri:      # 配置git仓库的地址
          search-paths: config                           # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                     # git仓库的账号
          password:

eureka:
  client:
    service-url:
      defaultZone: http://zone1:6200/eureka


