server:
  port: 6400

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadata-map:
      user.name: admin
      user.password: 123456
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:6200}/eureka/

spring:
  application:
    name: spring-cloud-admin-server
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
  security:
    user:
      name: admin
      password: 123456

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


